// <auto-generated />
using System;
using AppEntity.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApp.Migrations
{
    [DbContext(typeof(DbEntities))]
    [Migration("20210702062733_InitMigrate")]
    partial class InitMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppEntity.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 694, DateTimeKind.Local).AddTicks(5145),
                            Description = "Produce",
                            Name = "Produce"
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 695, DateTimeKind.Local).AddTicks(4114),
                            Description = "Groceries",
                            Name = "Groceries"
                        });
                });

            modelBuilder.Entity("AppEntity.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(7259),
                            Description = "Test",
                            ProductId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(7265),
                            Description = "My Order",
                            ProductId = 2
                        });
                });

            modelBuilder.Entity("AppEntity.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(5959),
                            DepartmentId = 1,
                            Description = "Tomatoes",
                            Name = "Tomatoes"
                        },
                        new
                        {
                            ProductId = 2,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(5968),
                            DepartmentId = 2,
                            Description = "Ginger",
                            Name = "Ginger"
                        },
                        new
                        {
                            ProductId = 3,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(5970),
                            DepartmentId = 2,
                            Description = "Brocolli",
                            Name = "Brocolli"
                        },
                        new
                        {
                            ProductId = 4,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(5971),
                            DepartmentId = 1,
                            Description = "Lettuce",
                            Name = "Lettuce"
                        },
                        new
                        {
                            ProductId = 5,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(5973),
                            DepartmentId = 2,
                            Description = "Baking Powder",
                            Name = "Baking Powder"
                        },
                        new
                        {
                            ProductId = 6,
                            CreatedBy = 1,
                            CreatedTime = new DateTime(2021, 7, 2, 12, 27, 32, 696, DateTimeKind.Local).AddTicks(5974),
                            DepartmentId = 1,
                            Description = "Chocolate",
                            Name = "Chocolate"
                        });
                });

            modelBuilder.Entity("AppEntity.Models.Order", b =>
                {
                    b.HasOne("AppEntity.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AppEntity.Models.Product", b =>
                {
                    b.HasOne("AppEntity.Models.Department", "Department")
                        .WithMany("Products")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AppEntity.Models.Department", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AppEntity.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
